language: node_js
node_js:
    - "8"
cache:
  directories:
  - node_modules

before_script:

script:
  - ganache-cli -p 7545 > /dev/null &
  - sleep 5
  - truffle compile
  - truffle migrate --network ganache --reset
deploy:
  on:
    branch:master
