language: node_js
  - "8"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle
  - ./startGanache.sh


script:
  - ganache-cli -p 8545 > /dev/null &
  - sleep 5
  - truffle compile
